import { glob } from "astro/loaders";
import { defineCollection } from "astro:content";
import { z } from "astro/zod";

const tools = defineCollection({
	// Load Markdown and MDX files in the `src/content/tools/` directory.
	loader: glob({ base: "./src/content/tools", pattern: "**/*.{md,mdx}" }),
	schema: z.object({
		name: z.string(),
		description: z.string(),
		descriptionEn: z.string(),
		category: z.string(),
		url: z.string(),
		affiliateUrl: z.string().optional(),
		logoUrl: z.string().optional(),
		price: z.string(),
		creator: z.string(),
		value: z.string(),
		valueEn: z.string(),
		featured: z.boolean().optional(),
		accentColor: z.string().optional(),
		// Redesign fields
		features: z.array(z.object({
			icon: z.string(),
			name: z.string(),
			nameEn: z.string(),
			desc: z.string(),
			descEn: z.string(),
		})).optional(),
		pricing: z.object({
			discount: z.string().optional(),
			discountEn: z.string().optional(),
			monthly: z.array(z.object({
				name: z.string(),
				tagline: z.string(),
				taglineEn: z.string(),
				price: z.string(),
				period: z.string(),
				periodEn: z.string(),
				annualNote: z.string(),
				annualNoteEn: z.string(),
				ctaText: z.string(),
				ctaTextEn: z.string(),
				popular: z.boolean().optional(),
				features: z.array(z.string()),
				featuresEn: z.array(z.string()),
			})),
			annual: z.array(z.object({
				name: z.string(),
				tagline: z.string(),
				taglineEn: z.string(),
				price: z.string(),
				period: z.string(),
				periodEn: z.string(),
				annualNote: z.string(),
				annualNoteEn: z.string(),
				ctaText: z.string(),
				ctaTextEn: z.string(),
				popular: z.boolean().optional(),
				features: z.array(z.string()),
				featuresEn: z.array(z.string()),
			})),
		}).optional(),
		steps: z.array(z.object({
			title: z.string(),
			titleEn: z.string(),
			desc: z.string(),
			descEn: z.string(),
			code: z.string().optional(),
		})).optional(),
		platforms: z.array(z.string()).optional(),
		rating: z.number().optional(),
		ratingCount: z.number().optional(),
		basedOn: z.string().optional(),
		aiModels: z.string().optional(),
		license: z.string().optional(),
		launchYear: z.string().optional(),
		comparisons: z.array(z.object({
			name: z.string(),
			specDriven: z.boolean(),
			baseEditor: z.string(),
			freeTier: z.boolean(),
			startingPrice: z.string(),
		})).optional(),
		limitations: z.object({
			title: z.string(),
			titleEn: z.string(),
			description: z.string().optional(),
			descriptionEn: z.string().optional(),
			headers: z.array(z.string()),
			headersEn: z.array(z.string()),
			rows: z.array(z.object({
				label: z.string(),
				labelEn: z.string(),
				values: z.array(z.string()),
				valuesEn: z.array(z.string()),
			})),
		}).optional(),
		coupons: z.array(z.object({
			code: z.string(),
			discount: z.string(),
			discountEn: z.string(),
			desc: z.string(),
			descEn: z.string(),
			expiry: z.string().optional(),
			expiryEn: z.string().optional(),
			terms: z.array(z.string()).optional(),
			termsEn: z.array(z.string()).optional(),
		})).optional(),
	}),
});

export const collections = { tools };
